### ISSUE TITLE
Add validations 

### ISSUE THREAD

**Issue by Camilo-J** [Camilo-J/Get-that-job-Api#3]
- [x] Validate unique applications_job
- [x] Validate unique followings
- [x] Add method to change application state when a Job is closed

**Comment by bettysl20** [comment]
- Validations para applications_job, solo permite guardar  si el user y job no existe en la tabla
- Validations para following, solo permite guardar si el user y datos de followable no existen en la tabla, es decir solo una vez puede un user estar siguiendo a una company o a un job
- Metodo,  cuando un job llega a tener el state = "closed", sus aplicaciones_job se ponen en "finished"

**Comment by Camilo-J** [comment]
LGTM!!!
